#!/bin/bash

# プロジェクト名
PROJECT_NAME="CraftCAD"

# ディレクトリ構造を定義
DIRECTORIES=(
  "$PROJECT_NAME"
  "$PROJECT_NAME/Model/Materials"
  "$PROJECT_NAME/Model/Designs/Components"
  "$PROJECT_NAME/Model/History"
  "$PROJECT_NAME/Model/Analysis"
  "$PROJECT_NAME/Model/Collaboration"
  "$PROJECT_NAME/View/Components/Buttons"
  "$PROJECT_NAME/View/Components/Pickers"
  "$PROJECT_NAME/View/Components/Viewers"
  "$PROJECT_NAME/View/Dialogs"
  "$PROJECT_NAME/View/Modes"
  "$PROJECT_NAME/ViewModel"
  "$PROJECT_NAME/Controller"
  "$PROJECT_NAME/Services"
  "$PROJECT_NAME/Utility"
  "$PROJECT_NAME/Plugins"
  "$PROJECT_NAME/Environment"
  "$PROJECT_NAME/Localization/Languages/en.lproj"
  "$PROJECT_NAME/Localization/Languages/ja.lproj"
  "$PROJECT_NAME/Localization/Languages/fr.lproj"
  "$PROJECT_NAME/Testing/UnitTests"
  "$PROJECT_NAME/Testing/UITests"
  "$PROJECT_NAME/Testing/PerformanceTests"
  "$PROJECT_NAME/ARVR/Tracking"
  "$PROJECT_NAME/Documentation"
  "$PROJECT_NAME/Assets.xcassets/Icons"
  "$PROJECT_NAME/Assets.xcassets/Images"
)

# ファイル構造を定義
FILES=(
  "$PROJECT_NAME/AppDelegate.swift"
  "$PROJECT_NAME/SceneDelegate.swift"
  "$PROJECT_NAME/Model/Materials/Wood.swift"
  "$PROJECT_NAME/Model/Materials/Metal.swift"
  "$PROJECT_NAME/Model/Materials/Plastic.swift"
  "$PROJECT_NAME/Model/Designs/2DDesign.swift"
  "$PROJECT_NAME/Model/Designs/3DDesign.swift"
  "$PROJECT_NAME/Model/Designs/Components/Screw.swift"
  "$PROJECT_NAME/Model/CuttingPlan.swift"
  "$PROJECT_NAME/Model/Paint.swift"
  "$PROJECT_NAME/Model/User.swift"
  "$PROJECT_NAME/Model/ARVRModel.swift"
  "$PROJECT_NAME/Model/History/DesignHistory.swift"
  "$PROJECT_NAME/Model/History/VersionControl.swift"
  "$PROJECT_NAME/Model/Analysis/Sustainability.swift"
  "$PROJECT_NAME/Model/Analysis/AIRecommendations.swift"
  "$PROJECT_NAME/Model/Collaboration/RealTimeCollaboration.swift"
  "$PROJECT_NAME/Model/Collaboration/CollaborationSettings.swift"
  "$PROJECT_NAME/View/Components/Buttons/PrimaryButton.swift"
  "$PROJECT_NAME/View/Components/Buttons/SecondaryButton.swift"
  "$PROJECT_NAME/View/Components/Pickers/MaterialPicker.swift"
  "$PROJECT_NAME/View/Components/Viewers/DesignViewer.swift"
  "$PROJECT_NAME/View/Dialogs/MaterialEditDialog.swift"
  "$PROJECT_NAME/View/Dialogs/ExportSettingsDialog.swift"
  "$PROJECT_NAME/View/Modes/PaintModeView.swift"
  "$PROJECT_NAME/View/Modes/WalkthroughModeView.swift"
  "$PROJECT_NAME/View/MainView.swift"
  "$PROJECT_NAME/View/SettingsView.swift"
  "$PROJECT_NAME/View/SimulationView.swift"
  "$PROJECT_NAME/View/CuttingPlanView.swift"
  "$PROJECT_NAME/View/ARVRView.swift"
  "$PROJECT_NAME/View/ExportView.swift"
  "$PROJECT_NAME/View/CollaborationView.swift"
  "$PROJECT_NAME/ViewModel/DesignViewModel.swift"
  "$PROJECT_NAME/ViewModel/UserViewModel.swift"
  "$PROJECT_NAME/ViewModel/3DModelViewModel.swift"
  "$PROJECT_NAME/ViewModel/SimulationViewModel.swift"
  "$PROJECT_NAME/ViewModel/CuttingPlanViewModel.swift"
  "$PROJECT_NAME/ViewModel/ModesViewModel.swift"
  "$PROJECT_NAME/ViewModel/ARVRViewModel.swift"
  "$PROJECT_NAME/ViewModel/CollaborationViewModel.swift"
  "$PROJECT_NAME/Controller/DesignController.swift"
  "$PROJECT_NAME/Controller/UserController.swift"
  "$PROJECT_NAME/Controller/SimulationController.swift"
  "$PROJECT_NAME/Controller/CuttingPlanController.swift"
  "$PROJECT_NAME/Controller/ExportController.swift"
  "$PROJECT_NAME/Controller/CollaborationController.swift"
  "$PROJECT_NAME/Controller/ARVRController.swift"
  "$PROJECT_NAME/Services/DesignService.swift"
  "$PROJECT_NAME/Services/UserService.swift"
  "$PROJECT_NAME/Services/APIService.swift"
  "$PROJECT_NAME/Services/ExportService.swift"
  "$PROJECT_NAME/Services/ImportService.swift"
  "$PROJECT_NAME/Services/SimulationService.swift"
  "$PROJECT_NAME/Services/CuttingPlanService.swift"
  "$PROJECT_NAME/Services/AnalyticsService.swift"
  "$PROJECT_NAME/Services/CollaborationService.swift"
  "$PROJECT_NAME/Services/HistoryService.swift"
  "$PROJECT_NAME/Utility/Constants.swift"
  "$PROJECT_NAME/Utility/Extensions.swift"
  "$PROJECT_NAME/Utility/Helpers.swift"
  "$PROJECT_NAME/Utility/Validators.swift"
  "$PROJECT_NAME/Utility/Formatters.swift"
  "$PROJECT_NAME/Utility/GeometryUtils.swift"
  "$PROJECT_NAME/Utility/FileUtils.swift"
  "$PROJECT_NAME/Utility/ColorUtils.swift"
  "$PROJECT_NAME/Utility/NetworkUtils.swift"
  "$PROJECT_NAME/Utility/ARUtils.swift"
  "$PROJECT_NAME/Utility/AnalyticsUtils.swift"
  "$PROJECT_NAME/Utility/StorageUtils.swift"
  "$PROJECT_NAME/Plugins/PluginManager.swift"
  "$PROJECT_NAME/Environment/DevelopmentConfig.swift"
  "$PROJECT_NAME/Environment/StagingConfig.swift"
  "$PROJECT_NAME/Environment/ProductionConfig.swift"
  "$PROJECT_NAME/Localization/Localizable.strings"
  "$PROJECT_NAME/Testing/UnitTests/ModelTests.swift"
  "$PROJECT_NAME/Testing/UnitTests/ServiceTests.swift"
  "$PROJECT_NAME/Testing/UnitTests/ViewModelTests.swift"
  "$PROJECT_NAME/Testing/UITests/SimulationUITests.swift"
  "$PROJECT_NAME/Testing/UITests/ARVRUITests.swift"
  "$PROJECT_NAME/Testing/UITests/CollaborationUITests.swift"
  "$PROJECT_NAME/Testing/PerformanceTests/RenderingPerformanceTests.swift"
  "$PROJECT_NAME/Testing/PerformanceTests/CuttingPlanPerformanceTests.swift"
  "$PROJECT_NAME/ARVR/ARView.swift"
  "$PROJECT_NAME/ARVR/VRView.swift"
  "$PROJECT_NAME/ARVR/Tracking/MarkerTracking.swift"
  "$PROJECT_NAME/ARVR/Tracking/EnvironmentTracking.swift"
  "$PROJECT_NAME/Documentation/API.md"
  "$PROJECT_NAME/Documentation/Architecture.md"
  "$PROJECT_NAME/Documentation/UserGuide.md"
  "$PROJECT_NAME/README.md"
)

# ディレクトリを作成
for dir in "${DIRECTORIES[@]}"; do
  mkdir -p "$dir"
done

# ファイルを作成
for file in "${FILES[@]}"; do
  if [[ $file == */ ]]; then
    mkdir -p "$file" # ディレクトリを作成
  else
    touch "$file" # ファイルを作成
  fi
done

echo "プロジェクト構造が作成されました: $PROJECT_NAME"
