#ifndef DIYCAD_FFI_H
#define DIYCAD_FFI_H

#pragma once

/* This file is generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

const char *diycad_version(void);

/**
 * # Safety
 *
 * `path` must be a valid, NUL-terminated C string pointer.
 * It may be null, in which case a negative error code is returned.
 */
int diycad_validate_project(const char *path);

#endif  /* DIYCAD_FFI_H */
